### ISSUE TITLE
Expects import "fyne.io/fyne/v2

### ISSUE THREAD

**Issue by zefrof** [unix-streamdeck/streamdeckui#1]
When I try to install streamdeckui (`go get github.com/unix-streamdeck/streamdeckui`) I get the following output:

```
go/src/github.com/unix-streamdeck/streamdeckui/button.go:7:2: code in directory /home/zefrof/go/src/fyne.io/fyne expects import "fyne.io/fyne/v2"
go/src/github.com/unix-streamdeck/streamdeckui/main.go:6:2: code in directory /home/zefrof/go/src/fyne.io/fyne/app expects import "fyne.io/fyne/v2/app"
go/src/fyne.io/fyne/internal/widget/base.go:7:2: code in directory /home/zefrof/go/src/fyne.io/fyne/canvas expects import "fyne.io/fyne/v2/canvas"
go/src/github.com/unix-streamdeck/streamdeckui/handler.go:6:2: code in directory /home/zefrof/go/src/fyne.io/fyne/dialog expects import "fyne.io/fyne/v2/dialog"
go/src/fyne.io/fyne/internal/driver/glfw/menu_bar.go:8:2: code in directory /home/zefrof/go/src/fyne.io/fyne/layout expects import "fyne.io/fyne/v2/layout"
go/src/fyne.io/fyne/internal/widget/scroller.go:8:2: code in directory /home/zefrof/go/src/fyne.io/fyne/theme expects import "fyne.io/fyne/v2/theme"
go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:16:2: code in directory /home/zefrof/go/src/fyne.io/fyne/widget expects import "fyne.io/fyne/v2/widget"
```
Seems there isn't a v2 folder for the install to target? Streamdeckd installed and runs without issue. Any help would be appreciated.

**Comment by The-Jonsey** [comment]
Hey, it seems the go.mod file wasn't configured properly, it should be fixed with the latest commit, try installing it again, and if you get the same error, it's probably go not trying the latest version, so try `go get -u github.com/unix-streamdeck/streamdeckui`

**Comment by zefrof** [comment]
Unfortunately even with `-u` in the `go get` command I'm still getting the same output. Should I give it a bit and try again later?

**Comment by andydotxyz** [comment]
Are you using a Go version that has modules turned off @zefrof?

Can you try with `GO111MODULE=on` to be sure?

**Comment by zefrof** [comment]
@andydotxyz my go version: `go version go1.15.5 linux/amd64`

Here's what I get when running `GO111MODULE=on go get -u github.com/unix-streamdeck/streamdeckui`:

```
go: github.com/unix-streamdeck/streamdeckui upgrade => v0.0.0-20210319180615-9899dcb6e7d4
go: github.com/stretchr/testify upgrade => v1.7.0
go: golang.org/x/sys upgrade => v0.0.0-20210319071255-635bc2c9138d
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: golang.org/x/text upgrade => v0.3.5
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: golang.org/x/image upgrade => v0.0.0-20210220032944-ac19c3e999fb
go: github.com/srwiley/oksvg upgrade => v0.0.0-20210209000435-a757b9cbd472
go: golang.org/x/net upgrade => v0.0.0-20210316092652-d523dce5a7f4
go: github.com/go-gl/glfw/v3.3/glfw upgrade => v0.0.0-20210311203641-62640a716d48
go: github.com/go-gl/gl upgrade => v0.0.0-20210315015930-ae072cafe09d
go: downloading golang.org/x/image v0.0.0-20210220032944-ac19c3e999fb
go: downloading golang.org/x/sys v0.0.0-20210319071255-635bc2c9138d
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/srwiley/oksvg v0.0.0-20210209000435-a757b9cbd472
go: downloading github.com/go-gl/gl v0.0.0-20210315015930-ae072cafe09d
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading golang.org/x/net v0.0.0-20210316092652-d523dce5a7f4
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20210311203641-62640a716d48
go: downloading golang.org/x/text v0.3.5
go: gopkg.in/yaml.v3 upgrade => v3.0.0-20210107192922-496545a6307b
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
# pkg-config --cflags  -- gl gl
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
pkg-config: exit status 1
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210311203641-62640a716d48/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
Sorry if these are rudimentary problems, I'd never messed with Go until yesterday.

**Comment by The-Jonsey** [comment]
It appears you don't have the dependencies for GFLW installed, you can find the required dependencies here, and how to install them on your distro here: https://github.com/go-gl/glfw#installation

**Comment by zefrof** [comment]
> It appears you don't have the dependencies for GFLW installed, you can find the required dependencies here, and how to install them on your distro here: https://github.com/go-gl/glfw#installation

That did it! Thank you both.
